#!/bin/bash
# This script is used to run one of the caom2 usage python scripts.

# Identify the working directory and script directory

if [ -d $HOME/work/caom2usage ]; then
    working_dir=$HOME/work/caom2usage
elif [ -d /arc/projects/CADC/caom2usage ]; then
    working_dir=/arc/projects/CADC/caom2usage
else
    echo "Neither $HOME/work/caom2usage nor /arc/projects/CADC/caom2usage exist!"
    exit 1
fi

# check if the git/cadc-tools directory exists

script_dir=$HOME/work/git/cadc-tools
if [ ! -d "$script_dir" ]; then
    echo "Directory $script_dir does not exist!"
    exit 1
fi

# Check if the script name is provided
if [ -z "$1" ]; then
    echo "Usage: $1 <script_name> [script_args]"
    echo "Example: $1 usageGenCollInstr [script_args]"
    echo "Example: $1 usageGenCollection [script_args]"
    echo "Example: $1 usagePrep"
    echo "Example: $1 usageSumCollInstr"
    echo "Example: $1 usageSumCollection"
    exit 1
fi 

# Check if the script exists
if [ ! -f "$script_dir/$1.py" ]; then
    echo "Script $1.py not found!"
    exit 1
fi     

cd $working_dir
python3 $script_dir/$1.py $2 $3 $4 $5 $6 $7 $8 $9
# Check if the script ran successfully
if [ $? -ne 0 ]; then
    echo "Script $1.py failed!"
    exit 1
fi  